### ISSUE TITLE
setting shift times in multiple locations

### ISSUE THREAD

**Issue by Saami** [brianmaissy/WSMA#19] opened 2011-11-27 23:07 UTC
(Logged in as a wsm) When you create a shift/chore you enter a day and time, but in “Allocate Shift” you can drag and drop that shift/chore to any slot... Why the inconsistency? might as will not as for a time when creating a chore if you are going to drag and drop it into any time slot. I will categorize this as trivial as it is more or less a cosmetic problem.

**Comment by brianmaissy** [comment] 2011-11-28 23:31
Duplicate of https://github.com/brianmaissy/WSMA/issues/4

**Closed as completed by brianmaissy** 2011-11-28 23:31 UTC
